spring.application.name=house-rental-system


spring.datasource.url=jdbc:postgresql://localhost:5432/house_rental_db
spring.datasource.username=epaphras
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Execute data.sql after schema is created by Hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true